### ISSUE TITLE
Evaluate contact form submission strategy

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/chicago-environment-explorer#83]
Currently this is handled with a Google script, would it be better to turn this into a Netlify form? We are starting to use Netlify for forms on other sites.

One thing to look for is where these form submissions are currently going and stored, and whether there are people getting alerts for these submissions who wouldn't be able to get alerts if we switched to Netlify.

**Comment by Makosak** [comment]
There are a few forms-- I thought the main chives/contact form goes to the HEROP Slack? Then there is a Resource Guide submission form, and a data submission form, which go to GoogleForms.

Pros for Google Script/Google: Shared google form repo where multiple groups can view/manage.

Cons: It's easy to miss, and not enough individuals are collectively co-viewing or co-managing. Missed a resource guide submission in the past because of that. For the general contact form, would agree that routing to the Slack of managing group is most efficient.

**Comment by mradamcox** [comment]
I spent the day working on this and finding a better solution so we don't miss submissions. I have written a lot more in our engineering Notion page, but ultimately I ended up creating a simple Slack App that our form submission hits directly, posting the form directly into a new channel that I made for it.

I left the previous setup in place because Slack integration on our free tier won't be retaining a full archive of submissions, and this Google Sheet setup does, basically, still work. However, 1) It points to the same sheet as the Covid Atlas form, so this is a little confusing (the sheet sits within that Drive directory, not the one for ChiVes), and 2) It is no longer integrated with Slack so we have missed submissions. I think it may have been connected via another app, Zapier, in the past, but that is no longer working.

So, for now we are posting directly to the Google Sheet (as before), _as well_ as posting directly into Slack via the new integration.
